---
name: Documentation

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/pdoc@239340ab15e2c96523fba82cb55a509f0a3b0b27 # v0
        with:
          docs-dependency-section: .[docs]
          gh-pages-publish-directory: ./html/fastest_races
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/fastest_races
          pyproject-toml: ./pyproject.toml
          python-version: "3.13"
          template-directory: ./documentation
