---
name: Documentation

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/pdoc@38f0d7e429cc1e3366331dba6ab7a656f9aa01e2 # v0
        with:
          docs-dependency-section: docs
          gh-pages-publish-directory: ./html/fastest_races
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/fastest_races
          pyproject-toml: ./pyproject.toml
          python-version: "3.13"
          template-directory: ./documentation
