---
name: Documentation

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/pdoc@d8081a80ce0003b82fc662944c69bb61db85e518 # v0
        with:
          docs-dependency-section: docs
          gh-pages-publish-directory: ./html/fastest_races
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/fastest_races
          pyproject-toml: ./pyproject.toml
          python-version: "3.13"
          template-directory: ./documentation
