---
name: Documentation

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/pdoc@ef8e8c4b69c12a799c90f4400a49ad1e9d3ee345 # v0
        with:
          docs-dependency-section: .[docs]
          gh-pages-publish-directory: ./html/fastest_races
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/fastest_races
          pyproject-toml: ./pyproject.toml
          python-version: "3.13"
          template-directory: ./documentation
