---
name: Test

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
        include:
          - os: macos-latest
            python-version: "3.13"
          - os: windows-latest
            python-version: "3.13"
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/tox@ef8e8c4b69c12a799c90f4400a49ad1e9d3ee345 # v0
        with:
          cache-path: .tox
          pyproject-toml: ./pyproject.toml
          python-version: ${{ matrix.python-version }}
